### ISSUE TITLE
API returns 'Forbidden'

### ISSUE THREAD

**Issue by dlebauer** [sckott/traitdb#2]
https://traits.party/ and all examples provided in #1 return 'Forbidden'

**Comment by sckott** [comment]
sorry bout that, there's some things to work out a bit, try these:

https://traits.party/heartbeat
https://traits.party/datasets/
https://traits.party/datasets/z85a07642-9f49-408c-a16f-f71135d9450f 
https://traits.party/datasets/z85a07642-9f49-408c-a16f-f71135d9450f/fields/ 
https://traits.party/datasets/z85a07642-9f49-408c-a16f-f71135d9450f/fetch

**Comment by sckott** [comment]
there's some issues i need to fix where if a path on the end is present or not makes a difference, so just add path on end or remote it if you get forbidden
